module.exports = {
	'admin':			require('./admin.js'),
	'ajax':				require('./ajax.js'),
	'base-component':	require('./base-component.js'),
	'block':			require('./block.js'),
	'cli':				require('./cli.js'),
	'compat':			require('./compat.js'),
	'core':				require('./core.js'),
	'cron':				require('./cron.js'),
	'git':				require('./git.js'),
	'model':			require('./model.js'),
	'network-admin':	require('./network-admin.js'),
	'network-settings':	require('./network-settings.js'),
	'posttype':			require('./posttype.js'),
	'rest':				require('./rest.js'),
	'settings':			require('./settings.js'),
	'shortcode':		require('./shortcode.js'),
	'taxonomy':			require('./taxonomy.js'),
	'widget':			require('./widget.js')
}
